version: "3.7"

networks:
  proxy:
    external: true

services: 
  oasa-api:
    image: geoza/oasa-backend
    container_name: OASA-API
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks: 
      - proxy
    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.nginx-secured.rule=Host(`api.oasa-telematics.com`)" # <== Your Domain Name for the https rule 
      - "traefik.http.routers.nginx-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.nginx-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https