version: "3.7"

networks:
  nginx:
    external: true

services: 
  oasa-api:
    image: geoza/oasa-backend
    container_name: OASA-API
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "3000:3000"
    networks: 
      - nginx