version: "3.7"

services: 
  OASA-API:
    image: geoza/oasa-backend
    container_name: OASA-API
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "3000:3000"